m0="Tagebuch des Oktavius:\n\n\nVierter Tag nach dem Schiffbruch.\n\n\nGestern fanden sich alle Überlebenden\nzusammen, um die Lage zu beraten. Da\nkeine Aussicht auf eine baldige Rettung\nbesteht, beschlossen wir, uns auf dieser\nfremden Insel niederzulassen. Dabei\nwerden uns die geretteten Güter aus dem\nSchiff eine große Hilfe sein. Das\nWichtigste wird sein, die Rohstoffe der Insel\nfür den Aufbau einer Siedlung nutzbar zu\nmachen. Wir benötigen dringend\nUnterkünfte für einen Holzfäller,\nSchreiner und den Steinmetz."
m1="Bauen Sie Unterkünfte für einen Holzfäller, Schreiner und Steinmetz."
m2="Achter Tag nach dem Schiffbruch.\n\n\nDie Grundlagen für den Aufbau unserer\nSiedlung sind geschaffen. Der\nBaumbestand in diesem Gebiet wird aber\nnicht lange vorhalten. Um die\nlangfristige Versorgung mit Holz zu\ngewährleisten, benötigen wir einen Förster.\n\n\nBauen Sie ein Forsthaus."
m3="Bauen Sie ein Forsthaus."
m4="Elfter Tag im zweiten Monat nach dem\nSchiffbruch.\n\n\nWir wissen immer noch nicht, ob wir\nalleine auf dieser Insel sind.\nVorsichtshalber sollten wir einen\nWachposten an den offenen Grenzen zum\nLandesinneren errichten.\n\n\nBauen Sie einen Wachposten an der nördlichen\nGrenze Ihrer Siedlung."
m5="Bauen Sie einen Wachposten an der nördlichen\nGrenze Ihrer Siedlung."
m6="Fünfter Tag im dritten Monat.\n\n\nDurch die Ausbreitung unseres Landes\nhaben wir den Berg im Norden erreicht.\nUnser Gelehrter sollte sich dort den\nBoden mal anschauen. Langfristig\nbrauchen wir Brennstoff, Baumaterial und\nnatürlich auch Waffen und Geld. Wir\nmüssen also Eisen, Gold, Kohle und\nGranit finden."
m7="Bauen Sie einen Weg auf den Berg und schicken\nSie Ihren Gelehrten dorthin."
m8="Sechzehnter Tag im sechsten Monat.\n\n\nWir haben Eisenerz gefunden und wären\njetzt in der Lage, Waffen zu\nproduzieren. Der weiteren Erkundung der\nInsel stünde dann nichts mehr im Wege.\nDazu müssen wir aber erst ein\nEisenbergwerk und die dazugehörige\nEisenschmelze bauen. Eine Waffenschmiede\nkönnte dann die Produktion von\nSchwertern und Schilden übernehmen. Wir\nmüssen aber auch die Bergarbeiter mit\nNahrungsmitteln versorgen. Unsere\nVorräte sind fast aufgebraucht. Wir\nbrauchen Jäger und Fischer!"
m9="Bauen Sie ein Eisenbergwerk, eine\nEisenschmelze und eine Waffenschmiede."
m10="Letzter Tag im achten Monat nach der Landung.\n\n\nNördlich unseres neuen Außenpostens\nliegt eine weite, fruchtbare Ebene. Dort\nergeben sich ganz neue Möglichkeiten,\nunsere Siedlung zu erweitern. Dazu\nbrauchen wir allerdings Soldaten."
m11="Erreichen Sie die nördliche Ebene."
m12="Zwölfter Tag des neunten Monats.\n\n\nNachdem wir weiter nach Norden\nvorgedrungen sind, haben wir die\nEbene erreicht. Endlich haben wir\ngenug Platz, um größere Gebäude und\nBauernhöfe errichten zu können. Jetzt\nwollen wir das umliegende Gebirge nach\nRohstoffen absuchen."
m13="Suchen Sie nach neuen Rohstoffen."
m14="Wir haben eine Goldader erschlossen und\nsind nun in der Lage, kostbare Münzen zu prägen.\nSo langsam wird das Leben hier\nbeinahe heimisch komfortabel."
m16="Die Versorgung der Schmelzereien ist\ngewährleistet: wir haben Kohle im\nwestlichen Gebirge gefunden. Nun können\nwir unsere Metallerze problemlos\nweiterverarbeiten. Alles entwickelt sich\nsehr gut."
m18="Da Gelehrte Granitvorkommen in den\nBergen gefunden haben, ist der Nachschub\nan Steinen bis auf weiteres gesichert."
m20="Unser Gelehrter hat eine Wasserader\ngefunden. Nun sind wir in der Lage mit\neinem Brunnen Wasser zu fördern."
m22="Wir haben die ersten Goldmünzen geprägt\nund können jetzt die Ausbildung unserer\nSoldaten bezahlen."
m24="Der Bau unserer ersten Getreidefarm\nist abgeschlossen. Das Getreide kann\nnun in der Mühle zu Mehl verarbeitet\noder auf dem Schweinehof verfüttert\nwerden. Die Versorgungslage wird immer\nbesser."
m26="Der neue Schweinehof garantiert eine\nsichere Versorgung unserer Metzgerei."
m28="Die Windmühle wird unsere Bäckerei\nmit ausreichend Mehl versorgen."
m30="Ein seltsames Ding haben unsere Gelehrten\nentdeckt. Es sieht aus wie ein Tor.\nOffensichtlich waren also doch bereits\nMenschen vor uns auf dieser Insel. Sogar\neine Inschrift in lateinischen Buchstaben\nentdeckten sie auf dem Tor. Sie ist sehr\nseltsam und widersprüchlich, vielleicht ein\nRätsel: 'Sede ad vagari!' 'Laß Dich nieder,\num weiterzuziehen!' Wer weiß, was das\nbedeutet?!"
m100="Zweiter Tag des dreizehnten Monats\nnach der Landung.\n\n\nGestern begann das zweite Jahr, und\nheute haben wir es geschafft. Der Aufbau\nunserer neuen Siedlung ist vollendet und\ndie Versorgung unserer Leute gesichert.\nUnd die Gelehrten berichten von seltsamen\nAktivitäten am Tor. Es sieht so aus, als\nhabe sich ein Weg geöffnet, der uns von\ndieser Insel wegführen kann. Das scheint\nder Sinn des Rätsels zu sein: Man muß\nsich niederlassen und siedeln, um\nweiterzukommen. Mal sehen. Vielleicht\nführen ja wirklich alle Wege nach Rom."
b="Tagebuch"
rttr.DisableBuilding(0)
rttr.EnableBuilding(0,17,19,33)
s=0
i=0
g=0
c=0
h=0
w=0
k=0
l=0
m=0
n=0
o=0
v=10000
f1=rttr.PostNewBuildings
f2=rttr.MissionStatement
f3=rttr.GetBuildingCount
function onStart()
rttr.ClearResources(0)
rttr.AddWares(0,23,15,24,12,31,20,19,2,32,2,20,4,11,12,0,12)
rttr.AddPeople(0,0,40,1,8,2,4,3,4,4,3,5,4,6,4,7,6,8,3,9,3,10,3,11,8,13,4,15,4,16,4,17,4,18,4,19,4,20,4,26,4,21,8,28,8,29,15)
end
function onGameFrame(gf)
if (gf % 20) ~= 0 then
return
end
if s==0 then
if (f3(0,17)>0) and (f3(0,19)>0) and (f3(0,33)>0) then
s=1
k=gf
rttr.EnableBuilding(0,20)
f1(0,20)
f2(0,b,m2)
elseif ((gf-k)%v)==0 then
f2(0,b,m1)
elseif gf==20 then
f2(0,b,m0)
end
elseif s==1 then
if f3(0,20)>0 then
s=2
k=gf
rttr.EnableBuilding(0,1)
f1(0,1)
f2(0,b,m4)
elseif ((gf-k)%v)==0 then
f2(0,b,m3)
end
elseif s==2 then
if ((gf-k)%v)==0 then
f2(0,b,m5)
end
elseif s==3 then
if i==1 then
rttr.EnableBuilding(0,12,24,26,18,22)
f1(0,12,24,26,18,22)
s=4
k=rttr.GetGF()
f2(0,b,m8)
elseif ((gf-k)%v)==0 then
f2(0,b,m7)
end
elseif s==4 then
if (f3(0,12)>0) and (f3(0,24)>0) and (f3(0,26)>0) then
s=5
k=gf
f2(0,b,m10)
elseif ((gf-k)%v)==0 then
f2(0,b,m9)
end
elseif s==5 then
if l==1 then
s=6
k=gf
rttr.EnableBuilding(0,37)
f1(0,37)
f2(0,b,m12)
end
elseif s==6 then
if (f3(0,37)>0) then
s=7
k=gf
rttr.EnableBuilding(0,31,28)
f1(0,31,28)
f2(0,b,m24)
end
elseif s==7 then
if (m==0) and (f3(0,28)>0) then
rttr.EnableBuilding(0,21)
f1(0,21)
f2(0,b, m26)
m=1
end
if (n==0) and (f3(0,31)>0) then
rttr.EnableBuilding(0,32)
f1(0,32)
f2(0,b,m28)
n = 1
end
end
if (g==1) and (rttr.GetWareCount(0,28) > 0) then
g=2
f2(0, b, m22)
end
end
function onOccupied(player, x, y)
if player ~= 0 then
return
end
if (s==2) then
if (x==35) and (y==28) then
s=3
k=rttr.GetGF()
f2(0,b,m6)
end
end
if (x==39) and (y==19) then
l=1
elseif (o<2) and (x==14) and (y==8) then
o=2
rttr.AddStaticObject(14,8,561,0xFFFF,2)
f2(0,b,m100)
end
end
function onExplored(player,x,y)
if player ~= 0 then
return
end
if (o==0) and (x==14) and (y==8) then
o=1
f2(0,b,m30)
end
end
function onResourceFound(player,x,y,t,q)
if t==0 then
if i==0 then
i=1
end
elseif t==1 then
if g==0 then
rttr.EnableBuilding(0,34,13)
f1(0,34,13)
f2(0,b,m14)
g=1
end
elseif t==2 then
if c==0 then
rttr.EnableBuilding(0,11)
f1(0,11)
f2(0,b,m16)
c=1
end
elseif t==3 then
if h==0 then
rttr.EnableBuilding(0,10)
f1(0,10)
f2(0,b,m18)
h=1
end
elseif t==4 then
if w==0 then
rttr.EnableBuilding(0,35)
f1(0,35)
f2(0,b,m20)
w=1
end
end
end